// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpjm5SN96cJvsn6xTEI9TVW6Y07CS6vjQ',
    appId: '1:1022245222510:web:1832bfb1a0789044b10e7f',
    messagingSenderId: '1022245222510',
    projectId: 'task-eaa78',
    authDomain: 'task-eaa78.firebaseapp.com',
    storageBucket: 'task-eaa78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ0h1hurnmseN3NpA2A0S1-Wvo1wTGHiY',
    appId: '1:1022245222510:android:899cb1eb007e49cfb10e7f',
    messagingSenderId: '1022245222510',
    projectId: 'task-eaa78',
    storageBucket: 'task-eaa78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQLMs5Dfg3QWIM5ytRMPEjseIy1x4xb54',
    appId: '1:1022245222510:ios:ac532d62e4b4bdd8b10e7f',
    messagingSenderId: '1022245222510',
    projectId: 'task-eaa78',
    storageBucket: 'task-eaa78.firebasestorage.app',
    iosBundleId: 'com.example.shodiyorTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQLMs5Dfg3QWIM5ytRMPEjseIy1x4xb54',
    appId: '1:1022245222510:ios:b8787b035fafccfbb10e7f',
    messagingSenderId: '1022245222510',
    projectId: 'task-eaa78',
    storageBucket: 'task-eaa78.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpjm5SN96cJvsn6xTEI9TVW6Y07CS6vjQ',
    appId: '1:1022245222510:web:cc54429a50ede4fab10e7f',
    messagingSenderId: '1022245222510',
    projectId: 'task-eaa78',
    authDomain: 'task-eaa78.firebaseapp.com',
    storageBucket: 'task-eaa78.firebasestorage.app',
  );
}
